export { parse } from "./parse"
export { parseExpression } from "./Expression"

// Order matters
import "./Every"
import "./Some"
import "./group"
import "./GreaterThan"
import "./GreaterThanOrEqual"
import "./LesserThan"
import "./LesserThanOrEqual"
import "./Or"
import "./Not"
import "./Property"
import "./Includes"
import "./StartsWith"
import "./EndsWith"
import "./Has"
import "./InfixOperator"
import "./Value"
import "./Is"
import "./ignore" // Reads every token and throws it away so that parsing is finite
